"""Added garbage requests table

Revision ID: 9938d395ac88
Revises: cf8c52a56238
Create Date: 2025-03-07 01:46:10.308862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9938d395ac88'
down_revision: Union[str, None] = 'cf8c52a56238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("name", sa.String, nullable=False),
        sa.Column("email", sa.String, unique=True, index=True),
        sa.Column("password", sa.String, nullable=False),
        sa.Column("role", sa.String, nullable=False),
    )

    op.create_table(
        "garbage_requests",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("collector_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("status", sa.String, default="pending"),
        sa.Column("created_at", sa.DateTime, default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime, default=sa.func.now(), onupdate=sa.func.now()),
        sa.Column("is_active", sa.Boolean, default=True),
        sa.Column('location', sa.String, nullable=False),
        sa.Column('description', sa.String, nullable=True),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("garbage_requests")
    op.drop_table("users")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
